# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4233856d3631b653ccbbac184585a3a6d2624c83221e31c8a88ae629ca8b1c689f32ae35ee3681db5700243acf8d9fdfa90908d4bd23a3afbe704d8f4dc2a5e7

test:
  secret_key_base: 2f334729be0d68a1d7940a7949518a23efccea3d9fa58228ec0ef69eec9915d80122eee8b7abde402c05671a40f3f11366a957e47eac41593f167da5233cd8de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
